version: '3'
services:
  adapter:
    build:
      context: .
    container_name: adapter
    environment:
      - RAILS_ENV=test
    depends_on:
      - postgresdb
      - materializedb
    volumes:
      - ./:/usr/src/activerecord_materialize_adapter
    networks:
      - default
    tty: true
    stdin_open: true

  postgresdb:
    image: postgres:13.3
    container_name: postgresdb
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - default

  materializedb:
    image: materialize/materialized:mzbuild-XVWAK24CHQBPRZUKRCMUAB5PT3HUF2X5
    container_name: materializedb
    ports:
      - "6875:6875"
    networks:
      - default

networks:
  default:
