adapter: materialize
host: <%= ENV["PGHOST"] || "materializedb" %>
port: <%= ENV["PGPORT"] || "6875" %>
database: <%= ENV["PGDATABASE"] || "materialize_adapter_test" %>
username: <%= ENV["PGUSER"] || "materialize" %>
password: <%= ENV["PGPASSWORD"] || "" %>
setup: default
