test:
  pg:
    adapter: postgresql
    host: postgresdb
    port: 5432
    username: postgres
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    database: materialize_adapter_test
  materialize:
    adapter: materialize
    host: "materializedb"
    port: "6875"
    database: "materialize_adapter_test"
    username: "materialize"
    setup: default
